### Numpy and Pandas

In [2]:
#import lib
import numpy as np
import pandas as pd

In [5]:
numbers = [1,2,3,4,5]
print np.mean(numbers)
print np.median(numbers)
print np.std(numbers)

3.0
3.0
1.41421356237


In [6]:
#numpy array
array_1 = np.array([1,3,5,8],float)
print array_1
array_2 = np.array([[1,2,3],[4,5,6]],float)
print array_2

[ 1.  3.  5.  8.]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [9]:
# read from array
print array_1[1]
print array_1[:2]
array_1[1] = 5.0
print array_1[1]

print array_2[1][1]
print array_2[1,:]
print array_2[:,2]

5.0
[ 1.  5.]
5.0
5.0
[ 4.  5.  6.]
[ 3.  6.]


In [10]:
# calc of array
array_1 = np.array([[1,2],[3,4]],float)
array_2 = np.array([[5,6],[7,8]],float)

print array_1 + array_2
print array_1 - array_2
print array_1 * array_2
print array_1 / array_2

[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [12]:
# dot product
array_1 = np.array([1,2,3],float)
array_2 = np.array([[6],[7],[8]],float)

print np.dot(array_1,array_2)

[ 44.]


### DataFrams of Pandas

Series is the one-dimensional object

DataFrame is the two-dimensional object

In [13]:
series = pd.Series(['Dave','Chen',42,-111111])
print series

0       Dave
1       Chen
2         42
3    -111111
dtype: object


In [15]:
series = pd.Series(['Dave','Chen',359,9001],index = ['Instructor','Curriculum Manager','Course Number','Power Level'])
print series

Instructor            Dave
Curriculum Manager    Chen
Course Number          359
Power Level           9001
dtype: object


In [17]:
#get data from Frame
print series['Instructor']

print series[['Instructor','Curriculum Manager']]

Dave
Instructor            Dave
Curriculum Manager    Chen
dtype: object


In [19]:
cuteness = pd.Series([1,2,3,4,5],index=['Cockroach','Fish','Mini Pig','Puppy','Kitten'])

print cuteness > 3              # compare with 3
print " "
print cuteness[cuteness > 3]    #choice the element which larger than 3

Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool
 
Puppy     4
Kitten    5
dtype: int64


#### DataFrame of the pandas

In [20]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data)
print football

   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012


In [21]:
print football.dtypes
print football.describe()
print football.head()
print football.tail()

losses     int64
team      object
wins       int64
year       int64
dtype: object
          losses       wins         year
count   8.000000   8.000000     8.000000
mean    6.625000   9.375000  2011.125000
std     3.377975   3.377975     0.834523
min     1.000000   4.000000  2010.000000
25%     5.000000   7.500000  2010.750000
50%     6.000000  10.000000  2011.000000
75%     8.500000  11.000000  2012.000000
max    12.000000  15.000000  2012.000000
   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012


In [30]:
#Create a DataFrame
countries = ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']

gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]

#actual it's also true if don't use the pd.Series

olympic_medal_counts_df = pd.DataFrame({'country_name':pd.Series(countries),
    'gold':pd.Series(gold),
    'silver':pd.Series(silver),
    'bronze':pd.Series(bronze)})

print olympic_medal_counts_df

    bronze    country_name  gold  silver
0        9    Russian Fed.    13      11
1       10          Norway    11       5
2        5          Canada    10      10
3       12   United States     9       7
4        9     Netherlands     8       7
5        5         Germany     8       6
6        2     Switzerland     6       3
7        1         Belarus     5       0
8        5         Austria     4       8
9        7          France     4       4
10       1          Poland     4       1
11       2           China     3       4
12       2           Korea     3       3
13       6          Sweden     2       7
14       2  Czech Republic     2       4
15       4        Slovenia     2       2
16       3           Japan     1       4
17       1         Finland     1       3
18       2   Great Britain     1       1
19       1         Ukraine     1       0
20       0        Slovakia     1       0
21       6           Italy     0       2
22       2          Latvia     0       2
23       1      

In [35]:
#get data from the DataFrame

data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data)

print football['year']

print football.year  #same as the football['year']

print football[['year','wins','losses']]




0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64
0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64
   year  wins  losses
0  2010    11       5
1  2011     8       8
2  2012    10       6
3  2011    15       1
4  2012    11       5
5  2010     6      10
6  2011    10       6
7  2012     4      12


In [41]:
print football.iloc[[0]]

print football.loc[[0]]

print football[3:4]

print football[football.wins > 10]

print football[(football.wins > 10) & (football.team == 'Packers')]

#just choice specify column

print football['team'][football.wins>10]

   losses   team  wins  year
0       5  Bears    11  2010
   losses   team  wins  year
0       5  Bears    11  2010
   losses     team  wins  year
3       1  Packers    15  2011
   losses     team  wins  year
0       5    Bears    11  2010
3       1  Packers    15  2011
4       5  Packers    11  2012
   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012
0      Bears
3    Packers
4    Packers
Name: team, dtype: object
